DROP TABLE IF EXISTS positions;
CREATE TABLE positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fen TEXT UNIQUE NOT NULL,
    moves TEXT DEFAULT NULL, 
    name TEXT,
    short_name TEXT,
    description TEXT,
    short_description TEXT,
    white_plan TEXT,
    black_counterplay TEXT,
    source TEXT,
    tags TEXT
);
INSERT INTO positions (fen, moves, name, short_name, description, short_description, white_plan, black_counterplay, source, tags) VALUES 
('rnbqkbnr/ppp1pppp/8/3p4/3P4/8/PPP1PPPP/RNBQKBNR w KQkq d6 0 2', '["d4", "d5"]', 'Queen''s Gambit', 'queens-gambit', 'The Queen''s Gambit is one of the oldest and most respected openings in chess. It begins with the moves: 1. d4 d5 2. c4 White offers a pawn to gain central control. Black can either accept or decline the gambit.', 'A classical opening where White sacrifices a pawn for central control.','<ul><li><strong>Queen''s Gambit Accepted (QGA):</strong> Black captures the c4 pawn, leading to dynamic play.</li><li><strong>Queen''s Gambit Declined (QGD):</strong> Black maintains the central structure with 2... e6.</li><li><strong>Slav Defense:</strong> Black plays 2... c6, reinforcing the d5 pawn.</li></ul>','<ul><li><strong>Albin Countergambit:</strong> Black responds with 2... e5, aiming for rapid development.</li><li><strong>Tarrasch Defense:</strong> Black plays 3... c5, challenging White''s center.</li><li><strong>Chigorin Defense:</strong> Black develops the knight early with 2... Nc6.</li></ul>','https://chess.fandom.com/wiki/Queen%27s_Gambit','openings'),
('rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2', '["e4", "e5"]', 'King''s Gambit', 'kings-gambit', '<p>The King''s Gambit is an aggressive chess opening that begins with the moves:</p><pre>1. e4 e5  2. f4</pre><p>White sacrifices a pawn to gain rapid development and open lines for an attack. It was a favorite of romantic era players and remains an exciting option for those who enjoy tactical play.</p>', 'White gambits the f-pawn to gain rapid development.', '<ul><li><strong>King''s Gambit Accepted (KGA):</strong> White can play 3. Nf3 to prevent ...Qh4+ and prepare to regain the pawn.</li><li><strong>Bishop''s Gambit:</strong> 3. Bc4 aims for quick piece activity and a rapid assault on f7.</li><li><strong>Muzio Gambit:</strong> A wild choice where White sacrifices a knight with 3. Nf3 g5 4. O-O to gain a strong initiative.</li></ul>', '<ul><li><strong>Classical Defense:</strong> 2... exf4 3. Nf3 g5 aims to hold onto the extra pawn and secure the king.</li><li><strong>Falkbeer Countergambit:</strong> 2... d5 counterattacks the center immediately.</li><li><strong>Modern Defense:</strong> 2... d6 avoids taking the gambit pawn and aims for solid development.</li></ul>', 'https://chess.fandom.com/wiki/King%27s_Gambit', 'openings'),
('rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2', '["e4", "c5"]', 'Sicilian  Defense', 'sicilian-defense', 'The Sicilian Defense is one of the most popular and aggressive responses to 1.e4. By playing 1...c5, Black immediately contests the center while aiming for asymmetrical pawn structures, leading to dynamic and counterattacking opportunities. The Sicilian is widely played at all levels, from club games to world championship matches.', 'A counter-attacking opening for Black starting with 1... c5.', '<p>White typically aims to control the center and launch an early kingside attack. Popular setups include the Open Sicilian (2.Nf3 followed by d4), where White trades a central pawn to gain quick development and open lines. Other approaches, such as the Closed Sicilian or the Alapin Variation (2.c3), seek to avoid sharp theoretical battles while maintaining a solid position.</p>', 'Black''s main strategy in the Sicilian revolves around counterattacks and creating imbalances. Depending on the variation, Black may seek queenside expansion (Najdorf, Scheveningen), rapid piece development (Dragon), or central counterplay (Taimanov, Kan). The typical idea is to delay direct engagement in the center while preparing a powerful counterstrike.', 'https://chess.fandom.com/wiki/Sicilian_Defense', 'openings'),
('rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2', '["e4", "e6"]', 'French Defense', 'french-defense', 'The French Defense (1.e4 e6) is a solid and resilient opening where Black immediately prepares to challenge White’s center with ...d5. It often leads to closed positions with pawn chains, requiring strategic maneuvering rather than immediate open tactical play. Black accepts a somewhat passive light-squared bishop in exchange for a strong central structure and counterplay opportunities.', 'Black responds with e6, aiming for solid structure.', 'White typically aims to establish central dominance with d4 and push e5 to gain space. In many lines, White seeks a kingside attack, often utilizing the f4-f5 pawn break and piece coordination against Black’s position. Alternatively, White can play more positionally, pressuring Black’s queenside weaknesses and restricting counterplay.', 'Black’s primary counterplay involves challenging White’s center with ...c5 or ...f6, depending on the variation. The typical plans include attacking White’s pawn chain from the base, seeking counterplay on the queenside (as in the Winawer), or preparing a counterstrike in the center. Over time, Black''s solid structure and well-timed breaks can lead to powerful counterattacks.', 'https://chess.fandom.com/wiki/French_Defense', 'openings'),
('rnbqkbnr/pp1ppppp/2p5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2', '["e4", "c6"]', 'Caro-Kann Defense', 'caro-kann-defense', 'The Caro-Kann Defense (1.e4 c6) is a highly solid and resilient opening that emphasizes structure and long-term defensive stability. By preparing ...d5, Black immediately challenges White’s central control while avoiding the structural weaknesses seen in other 1.e4 defenses. The Caro-Kann is favored by players who prefer strategic maneuvering over sharp tactical battles.', 'A solid defense for Black focusing on c6 and d5.', 'White typically seeks an early space advantage and rapid piece development. The Advance Variation (2.d4 d5 3.e5) allows White to gain space and launch a kingside attack, while the Classical Variation (2.d4 d5 3.Nc3 or 3.Nd2) aims for steady development and pressure on Black’s center. Some lines, like the Panov-Botvinnik Attack, introduce early tactical play and an isolated queen’s pawn structure.', 'Black’s strategy revolves around solid development and well-timed breaks, such as ...c5 or ...f6, to undermine White’s center. In the Classical Variation, Black develops pieces harmoniously, often fianchettoing the light-squared bishop. In the Advance Variation, Black counters White’s space gain with precise piece placement and a timely ...c5 break. The Caro-Kann’s durability allows Black to reach favorable endgames with strong pawn structures.', 'https://chess.fandom.com/wiki/Caro-Kann_Defense', 'openings'),
('r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3', '["e4", "e5", "Nf3", "Nc6", "Bb5"]', 'Ruy Lopez', 'ruy-lopez', 'The Ruy Lopez (1.e4 e5 2.Nf3 Nc6 3.Bb5) is one of the most classical and strategically rich openings in chess. White immediately pressures Black’s knight on c6, which defends the e5 pawn, aiming for long-term positional advantages rather than immediate material gain. The opening often leads to deep middlegame plans and complex maneuvering, making it a staple in high-level play.', 'A classical opening focusing on central control.', 'White typically seeks central dominance with d4 and piece activity, aiming for kingside pressure or a slow buildup. In the Closed Ruy Lopez, White often maneuvers knights (e.g., Nb1-d2-f1-g3) and prepares f2-f4 to attack. In the Open Ruy Lopez, White plays dynamically, using quick piece play and targeting Black’s slightly compromised pawn structure.', 'Black has multiple ways to respond, including the solid Morphy Defense (...a6 and ...b5), the active Open Ruy Lopez (...Nxe4), or counterattacking setups like the Marshall Attack. Black typically looks to establish a strong central presence, challenge White’s space advantage with ...d5, or seek queenside expansion while maintaining solid defensive resources.', 'https://chess.fandom.com/wiki/Ruy_Lopez', 'openings'),
('rnb1kbnr/pppp1ppp/4p3/8/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3', '["f3","e6","g4","Qh4#"]', 'Fool''s Mate', 'fools-mate', 'A position to be avoided at all costs, the fool''s mate is the most famous move 2 mate.', 'A position to be avoided at all costs, the fool''s mate is the most famous move 2 mate.','In this case white ignores the possibility of an aggresive Queen opening and leaves the King with no escape.','As black, if you are playing against a novice player, it''s considered more honorable to alert the player to their folly before devastating them, but if you''re playing in a tournament or are Magnus Carlson, then devastate away.', 'https://chess.fandom.com/wiki/Fool%27s_mate', 'opening'),
('r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 0 4', '["e4","e5","Bc4","Nc6","Qh5","Nf6","Qf7#"]', 'Scholar''s Mate', 'scholars-mate', 'Similar to the fool''s mate, the scholar''s mate is another famous early game win, but this time in white''s favor. In this version you'' open with a standard e4, but quickly shift to your Bishop and Queen for a decisive attack on your opponent''s king.', 'Similar to the fool''s mate, the scholar''s mate is another famous early game win, but this time in white''s favor. In this version you'' open with a standard e4, but quickly shift to your Bishop and Queen for a decisive attack on your opponent''s king.', 'Moving the queen at the beginning of the game is unwise, as Black will usually try to chase it away with tempo. Playing 2...g6, which block the Queen from the f7 pawn, is unwise, as seen below:<pre class="bg-glass-dark-3">e4 e5<br>Qh5?! g6?<br>Qxe5+ Qe7<br>Qxh8 (Losing the rook and threatening the g8 Knight along with the whole kingside)</pre>White gains a huge advantage in this scenario. Instead, it is better to play:<pre class="bg-glass-dark-3">e4 e5<br>Qh5?! Nc6 (protecting the pawn)<br>Bc4 g6! (attacking the queen and protecting the vital f7 square)<br>Qf3 Nf6 (4...Bg7?? 5.Qxf7#) (Blocking the White Queen''s access to the f7 pawn)</pre>Play usually continues with Black fianchettoing his black-square Bishop (placing the Bishop along the longest diagonal) (5.Nc3 Bg7) and gaining a positional advantage.', 'The principal behind this move is to attack the weakest point in black''s defense: f7. The d7 and e7 squares both have 4 defenders at the start of the game while the f7 square only has one. This weakness can be exploited by two mobile pieces very quickly, the Bishop on c1 and the White Queen.', 'https://chess.fandom.com/wiki/Scholar%27s_Mate', 'opening'),
('r1bq1rk1/pp3ppp/2n1pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQK2R w KQ - 0 7', null, 'Pawn Breaks', 'pawn-breaks', 'A pawn break is a pawn move that opens up the position by attacking enemy pawns, forcing them to capture. The name "pawn break" supposedly is dubbed as such because it breaks up the enemy''s Pawn Structure.', 'short_description', 'white_plan', 'black_counterplay', 'https://chess.fandom.com/wiki/Pawn_Break#:~:text=Pawn%20breaks%20are%20helpful%20for,which%20are%20closed%20by%20pawns.&text=White''s%20only%20sensible%20option%20is,to%20release%20the%20d%2Dfile.', 'source', 'midgame');

INSERT INTO positions (fen, moves, name, short_name, description, short_description, white_plan, black_counterplay, source, tags) VALUES 
('r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 0 4', '["e4","e5","Bc4","Nc6","Qh5","Nf6","Qf7#"]', 'Scholar''s Mate', 'scholars-mate', 'Similar to the fool''s mate, the scholar''s mate is another famous early game win, but this time in white''s favor. In this version you'' open with a standard e4, but quickly shift to your Bishop and Queen for a decisive attack on your opponent''s king.', 'Similar to the fool''s mate, the scholar''s mate is another famous early game win, but this time in white''s favor. In this version you'' open with a standard e4, but quickly shift to your Bishop and Queen for a decisive attack on your opponent''s king.', 'Moving the queen at the beginning of the game is unwise, as Black will usually try to chase it away with tempo. Playing 2...g6, which block the Queen from the f7 pawn, is unwise, as seen below:<pre class="bg-glass-dark-3">e4 e5<br>Qh5?! g6?<br>Qxe5+ Qe7<br>Qxh8 (Losing the rook and threatening the g8 Knight along with the whole kingside)</pre>White gains a huge advantage in this scenario. Instead, it is better to play:<pre class="bg-glass-dark-3">e4 e5<br>Qh5?! Nc6 (protecting the pawn)<br>Bc4 g6! (attacking the queen and protecting the vital f7 square)<br>Qf3 Nf6 (4...Bg7?? 5.Qxf7#) (Blocking the White Queen''s access to the f7 pawn)</pre>Play usually continues with Black fianchettoing his black-square Bishop (placing the Bishop along the longest diagonal) (5.Nc3 Bg7) and gaining a positional advantage.', 'The principal behind this move is to attack the weakest point in black''s defense: f7. The d7 and e7 squares both have 4 defenders at the start of the game while the f7 square only has one. This weakness can be exploited by two mobile pieces very quickly, the Bishop on c1 and the White Queen.', 'https://chess.fandom.com/wiki/Scholar%27s_Mate', 'opening');